services:
  postgres:
    image: postgres:15
    container_name: courses-app_postgres
    environment:
      POSTGRES_USER: courses_app
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: courses_app_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: courses-app_redis
    environment:
      REDIS_PASSWORD: qwerty321
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
